### ISSUE TITLE
make into pip package

### ISSUE THREAD

**Issue by jtoy** [jtoy/sensenet#1]

**Comment by kiryteo** [comment]
I would like to work on this issue.!

**Comment by jtoy** [comment]
@kiryteo great, please do,  I got part of it working, but it doesnt  include the data directory which we need: 
https://github.com/jtoy/sensenet/tree/master/sensenet/envs/handroid/data
Im not sure if there is a way to unit test if a pip install works.

**Comment by kiryteo** [comment]
Sorry for late reply, I am working on this.

**Comment by jtoy** [comment]
great

**Comment by kiryteo** [comment]
Hey, I have created the distribution package, just it can't be uploaded with same name 'sensenet' as you have uploaded a version for it on Dec 10, 2017 - sensenet 0.0.1, I'll just make a PR containing 'dist' folder which you can upload on pypi.!

**Comment by jtoy** [comment]
commented: https://github.com/jtoy/sensenet/pull/31
