### ISSUE TITLE
better error if path to dataset not found

### ISSUE THREAD

**Issue by jtoy** [jtoy/sensenet#20]
better error if path to dataset not found, this is current error: 

python reinforce.py --data_path=../concave_objects --render --obj_type=obj
pybullet build time: Nov 30 2017 10:16:07
Vendor: NVIDIA Corporation
Renderer: NVIDIA GeForce GT 750M OpenGL Engine
Version: 4.1 NVIDIA-10.4.2 310.41.35f01
GLSL: 4.10
b3Printf: Selected demo: Physics Server
startThreads creating 1 threads.
starting thread 0
started thread 0
MotionThreadFunc thread started
Traceback (most recent call last):
  File "reinforce.py", line 192, in <module>
    env = SenseEnv(vars(args))
  File "../env.py", line 47, in __init__
    self.load_object()
  File "../env.py", line 78, in load_object
    stlfile = files[random.randrange(0,files.__len__())]
  File "/Users/jtoy/miniconda3/lib/python3.6/random.py", line 198, in randrange
    raise ValueError("empty range for randrange() (%d,%d, %d)" % (istart, istop, width))
ValueError: empty range for randrange() (0,0, 0)
numActiveThreads = 0
stopping threads
stopThreads: Thread 0 used: 1
Thread with taskId 0 exiting
Thread TERMINATED
destroy semaphore
semaphore destroyed
destroy main semaphore
main semaphore destroyed

**Comment by cryptomental** [comment]
https://github.com/jtoy/sensenet/pull/22

**Comment by jtoy** [comment]
Awesome, thank you!
